{% set name = "sbmlmath" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sbmlmath-{{ version }}.tar.gz
  sha256: 1c0c7b57b9bacef73bc0adc5443c1e2633ae1d2548086ab768fa2e7a03ac3c31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - python-libsbml >=5.20.4
    - sympy
    - pint
    - lxml >=4.6.4

test:
  imports:
    - sbmlmath
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dweindl/sbmlmath
  summary: SBML Math <-> SymPy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - kaiserls
    - dweindl
